- name: install tamandua dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-colorama
    - python3-flask

- name: clone tamandua git repository into opt
  git:
    repo: git@gitlab.phys.ethz.ch:amartako/Tamandua.git
    dest: /opt/Tamandua
    accept_hostkey: yes
    clone: yes

- name: run tamandua mail parser
  command: /opt/Tamandua/tamandua_parser.py /opt/Tamandua/mock_logs/extern-intern_to_intern.log --no-print creates=/opt/Tamandua/mails.data

- name: install apache2 package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - libapache2-mod-wsgi-py3

- name: populate apache2 config
  copy:
    src: tamandua.conf
    dest: /etc/apache2/sites-available/tamandua.conf

- name: enable wsgi apache2 module
  apache2_module:
    name: wsgi
    state: present

- name: disable default apache2 site
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: enable tamandua apache2 site
  file:
    src: /etc/apache2/sites-available/tamandua.conf
    dest: /etc/apache2/sites-enabled/tamandua.conf
    state: link
  notify:
    - restart apache2