- name: install tamandua dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip
    - python3-colorama
    - python3-flask
    - python3-flask-restful
    - python3-pymongo
    - python3-setuptools

- name: clone tamandua git repository into opt
  git:
    repo: git@gitlab.phys.ethz.ch:mailserver/Tamandua.git
    dest: "{{ tamandua_dir }}"
    accept_hostkey: yes
    clone: yes

- name: Create Tamandua user
  user:
    name: tamandua
    createhome: yes
    state: present

- name: Set permissions of Tamandua folder
  file:
    path: "{{ tamandua_dir }}"
    recurse: yes
    owner: tamandua
    group: tamandua

- name: Add MongoDB repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add MongoDB repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present
    filename: mongodb-org-3.4.list
    update_cache: yes

- name: Install MongoDB packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - mongodb-org

- name: enable and start mongod service
  service:
     name: mongod
     state: started
     enabled: yes

- name: install apache2 package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - libapache2-mod-wsgi-py3

- name: create apache sites-common folder
  file:
    state: directory
    path: /etc/apache2/sites-common

- name: populate apache2 common config
  copy:
    src: sites-common/tamandua.conf
    dest: /etc/apache2/sites-common/tamandua.conf
  notify:
    - restart apache2


- name: populate apache2 config
  copy:
    src: tamandua.conf
    dest: /etc/apache2/sites-available/tamandua.conf
  notify:
    - restart apache2


- name: populate apache2 conf-available
  copy:
    src: ldaps-certificate.conf
    dest: /etc/apache2/conf-available/ldaps-certificate.conf
  notify:
    - restart apache2

- name: create /opt/certs folder for certificates
  file:
    state: directory
    path: /opt/certs

- name: generating self signed certificate
  command: creates="/opt/certs/tamandua.crt" openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/certs/tamandua.key -out /opt/certs/tamandua.crt -subj "/C=CH/ST=Switzerland/L=Zurich/O=ETHZ/OU=ISG D-PHYS/CN=tamandua.ethz.ch"

- name: enable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ldap
    - authnz_ldap
    - wsgi
    - rewrite
    - ssl
  notify:
    - restart apache2

- name: disable default apache2 site
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache2

- name: enable tamandua apache2 site
  file:
    src: /etc/apache2/sites-available/tamandua.conf
    dest: /etc/apache2/sites-enabled/tamandua.conf
    state: link
  notify:
    - restart apache2

- name: enable apache2 conf-available
  file:
    src: /etc/apache2/conf-available/ldaps-certificate.conf
    dest: /etc/apache2/conf-enabled/ldaps-certificate.conf
    state: link
  notify:
    - restart apache2

- name: install tamandua cronjobs
  template:
    src: "{{ item }}"
    dest: /etc/cron.d/"{{ item }}"
    mode: 644
  with_items:
    - tamandua_cron
    - mongodb_dump_cron
    - tamandua_build_cache
